CREATE TABLE VOCABULARY (
    ID INT NOT NULL,
    WORD CHAR(100) NOT NULL,
    PRONOUNCE CHAR(100) NOT NULL,
    TRANSLATION CHAR(100) NOT NULL,
    LEARN_TIMES INT DEFAULT 0 NOT NULL,
    DNK_TIMES INT DEFAULT 0 NOT NULL,
    HM_TIMES INT DEFAULT 0 NOT NULL,
    KIM_TIMES INT DEFAULT 0 NOT NULL,
    LEARN_SCORE REAL DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (WORD)
);